cms_page_index:
    path:     /
    defaults: { _controller: "CMSBundle:Page:index" }
    methods:  GET

cms_page_show:
    path:     /{id}/show
    defaults: { _controller: "CMSBundle:Page:show" }
    methods:  GET

cms_page_new:
    path:     /new
    defaults: { _controller: "CMSBundle:Page:new" }
    methods:  [GET, POST]

cms_page_edit:
    path:     /{id}/edit
    defaults: { _controller: "CMSBundle:Page:edit" }
    methods:  [GET, POST]

cms_page_delete:
    path:     /{id}/delete
    defaults: { _controller: "CMSBundle:Page:delete" }
    methods:  DELETE
